# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'

target 'WhatFlower' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WhatFlower
pod 'Alamofire', '~> 5.5'
pod 'SwiftyJSON'
pod 'SDWebImage', '~> 5.12'
pod 'ColorThiefSwift'


end
